import { IColor } from '../constants/interface';

export const LightColors: IColor = {
  LOGO: '#374A5C',
  Background: {
    THEME: '#00CCBC',
    SWIPE_CARD_DELETE: '#FF665D',
    BLACK_BUTTON: '#1D1B20',
    WARNING: 'rgba(255, 14, 0, 0.1)',

    AVATAR_EDIT: '#006FFD',
    ICON_BUTTON: '#F4F4F4',
    PRIMARY: '#FFFFFF',
    LIGHT_THEME: '#80E2C9',
    BLACK_TRANSPARENT: 'rgba(0, 0, 0, 0.5)',
    NOTIFICATION: 'rgba(92,208,130,0.1)',
    LINE: '#C5C6CC',
    BIOMETRICS: '#F0F0F0',
    ICON: '#898A8D',
    TAB_BAR: '#FFFFFF',
    REDUCED_THEME: 'rgba(92,208,130,0.1)',
    SUB_SECTION: '#F6F6F6',
    TEXT_INPUT: '#FFFFFF',
    BACK_BUTTON: '#F4F4F4',
    HELPER: '#E2E2E2',
    WEEKDAYS: '#FAFCFE',
    DATE_CIRCLE: '#90DFAA',
    DOCUMENT_DEFAULT: '#F5F5F5',
    DELETE_ICON: '#FFD8D9',
    MULTI_SELECT_CARD: '#E3FFEC',
    SLIDER: '#00862C',
    SWIPE_CARD: '#EFFFF5',
    LIGHT_DOCUMENT: '#F1FFF6',
    DARK_DESCRIPTION: '#666666',
    STATUS_CHIP: '#FFA500',
    MORE_ICON_BUTTONS: '#EFEFEF',
  },
  Border: {
    DEFAULT: '#FFFFFF',
    PRIMARY: '#F0F0F0',
    TEXT_INPUT: '#BEBEBE',
    TEXT_INPUT_DEFAULT_BORDER: '#E2E8F0',
    TEXT_INPUT_FOCUSED_BORDER: '#94A3B8',
    THEME: '#00CCBC',
    DASHED: '#B7B7B7',
  },
  Button: {
    ACCENT: '#FFFFFF',
    ACCENT_BORDER: '#B4B4B4',
    BLACK: '#000000',
    DARK_DISABLED: '#324A5E',
    DISABLED: '#B1B1B1',
    ERROR: '#FF2C20',
    PRIMARY: '#00CCBC',
    SECONDARY_BLUE: '#006FFD',
    DESCRIPTION_ICON: '#64748B',
    LIGHT_RED: '#F9DADA',
    LIGHT_GRAY: '#727272',
    BUTTON_TEXT: '#dedbdbff',
    FACEBOOK: '#4267b2',
  },
  Chip: {
    DISABLED: '#B7B7B7',
    LIGHT_DISABLED: '#F0F0F0',
    LIGHT_THEME: '#CAFFDB',
    THEME: '#00CCBC',
    LIGHT_DEFAULT: '#E2E8F0',
  },
  Icon: {
    PRIMARY: '#000000',
    ACCENT: '#FFFFFF',
    THEME: '#00CCBC',
    ERROR: '#FF5252',
    DISABLED: '#71727A',
    BLENDING: '#5CD082',
    TabBar: {
      ACTIVE: '#00CCBC',
      INACTIVE: '#B1B1B1',
    },
    ACCORDION: '#64748B',
    FORWARD_ARROW: '#343330',
  },
  Shimmer: {
    END: '#DCDCDC',
    START: '#F6F6F6',
  },
  Text: {
    ACCENT: '#FFFFFF',
    DESCRIPTION: '#64748B',
    DISABLED: '#71727A',
    ERROR: '#FF5252',
    ICON_BUTTON: '#324A5E',
    LIGHT_DISABLED: '#F0F0F0',
    LIGHT_THEME: '#CAFFDB',
    PRIMARY: '#000000',
    THEME: '#00CCBC',
    LIGHT_DESCRIPTION: '#AEAEAE',
    AMOUNT: '#666666',
    LIGHT_AMOUNT: '#038200',
    Chip: {
      ACTIVE: '#000000',
      INACTIVE: '#B1B1B1',
    },
  },
  TextInput: {
    CURSOR: '#C4C4C5',
    PLACEHOLDER: '#BEBEBE',
    VALUES: '#000000',
    DEFAULT: '#FFFFFF',
  },
  Toggle: {
    OFF: '#AEAEAE',
    ON: '#00CCBC',
    KNOB: '#FFFFFF',
  },
  Gradient: {
    PRIMARY: '#00CCBC',
    SECONDARY: '#FFFFFF',
  },
  ProgressBar: {
    PRIMARY: '#00CCBC',
    UNFILLED: 'rgba(217,217,217,0.2)',
    DISABLED: '#F6F6F6',
  },
  SHADOW: {
    BACKGROUND: '#000000',
    LIGHT_BG: '#252424ff',
  },
  TRANSPARENT: 'transparent',
};

export const DarkColors: IColor = {
  ...LightColors,
  LOGO: '#FFFFFF',
  Background: {
    ...LightColors.Background,
    PRIMARY: '#2F303F',
    ICON_BUTTON: '#3A3B4A',
    TAB_BAR: '#2F303F',
    SUB_SECTION: '#3A3B4A',
    TEXT_INPUT: '#3A3B4A',
    BIOMETRICS: '#3A3B4A',
    BACK_BUTTON: 'TRANSPARENT',
    HELPER: '#1E2038',
  },
  Text: {
    ...LightColors.Text,
    PRIMARY: '#FFFFFF',
    ACCENT: '#FFFFFF',
    ICON_BUTTON: '#FFFFFF',
    DESCRIPTION: '#FAFAFA',
    DISABLED: '#EBEBE4',
    Chip: {
      ACTIVE: '#000000',
      INACTIVE: '#FFFFFF',
    },
  },
  TextInput: {
    ...LightColors.TextInput,
    CURSOR: '#C4C4C5',
    PLACEHOLDER: '#BEBEBE',
    VALUES: '#FFFFFF',
    DEFAULT: '#FFFFFF',
  },
  Icon: {
    ...LightColors.Icon,
    PRIMARY: '#FFFFFF',
    ACCENT: '#FFFFFF',
    ACCORDION: '#EBEBE4',
    BLENDING: '#5CD082',
    DISABLED: '#FFFFFF',
  },
  Chip: {
    ...LightColors.Chip,
    DISABLED: '#2F303F',
    LIGHT_DISABLED: '#3A3B4A',
  },
  Border: {
    ...LightColors.Border,
    PRIMARY: '#515A5C',
  },
};

